//
//  Key.swift
//  MenuBarUSB
//
//  Created by Rafael Neuwirth Swierczynski on 30/08/25.
//

enum Key {
    static let launchAtLogin = "launchAtLogin"
    static let showPortMax = "showPortMax"
    static let convertHexa = "convertHexa"
    static let longList = "longList"
    static let hideTechInfo = "hideTechInfo"
    static let renamedDevices = "renamedDevices"
    static let storedDevices = "storedDevices"
    static let inheritedDevices = "inheritedDevices"
    static let camouflagedDevices = "camouflagedDevices"
    static let renamedIndicator = "renamedIndicator"
    static let camouflagedIndicator = "camouflagedIndicator"
    static let showNotifications = "showNotifications"
    static let reduceTransparency = "reduceTransparency"
    static let disableNotifCooldown = "disableNotifCooldown"
    static let disableInheritanceLayout = "disableInheritanceLayout"
    static let forceDarkMode = "forceDarkMode"
    static let forceLightMode = "forceLightMode"
    static let increasedIndentationGap = "increasedIndentationGap"
    static let hideSecondaryInfo = "hideSecondaryInfo"
    static let hideUpdate = "hideUpdate"
    static let hideDonate = "hideDonate"
    static let noTextButtons = "noTextButtons"
    static let hideCount = "hideCount"
    static let numberRepresentation = "numberRepresentation"
    static let macBarIcon = "macBarIcon"
    static let hideMenubarIcon = "hideMenubarIcon"
    static let switchSides = "switchSides"
    static let restartButton = "restartButton"
    static let mouseHoverInfo = "mouseHoverInfo"
    static let profilerButton = "profilerButton"
    static let disableContextMenuSearch = "disableContextMenuSearch"
    static let searchEngine = "searchEngine"
    static let showEthernet = "showEthernet"
    static let internetMonitoring = "internetMonitoring"
    static let trafficButton = "trafficButton"
    static let disableTrafficButtonLabel = "disableTrafficButtonLabel"
    static let newVersionNotification = "newVersionNotification"
    static let contextMenuCopyAll = "contextMenuCopyAll"
    static let fastMonitor = "fastMonitor"
    static let settingsCategory = "settingsCategory"
    static let storeDevices = "storeDevices"
    static let storedIndicator = "storedIndicator"
}
